version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: logistic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/logistic?schema=public
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db_data:

