export enum LogisticState {
  DRAFT = 'DRAFT',
  CHECK_PENDING = 'CHECK_PENDING',
  CHECK_IN_PROGRESS = 'CHECK_IN_PROGRESS',
  CHECK_FINALIZED = 'CHECK_FINALIZED',
  ASSIGNED = 'ASSIGNED',
  READY = 'READY',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
